// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/yc-battle-arena/Arena.tsx": () => import("../components/mockups/yc-battle-arena/Arena.tsx"),
  "./components/mockups/yc-battle-arena/Current.tsx": () => import("../components/mockups/yc-battle-arena/Current.tsx")
};
